version: 0.0
os: linux
files:
  - source: /    # This copies everything from the repository
    destination: /var/www/myapp   # This is the directory on EC2 where files will be copied

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
