version: 0.0
os: linux
files:
  - source: /    # Copy everything from the repo
    destination: /var/www/myapp
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
